package provisioner

import (
	"bufio"
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"time"

	"github.com/takutakahashi/agentapi-proxy/pkg/sessionsettings"
	corev1 "k8s.io/api/core/v1"
	k8serrors "k8s.io/apimachinery/pkg/api/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/client-go/kubernetes"
	"k8s.io/client-go/rest"
)

const (
	piOllamaDefaultModel = "glm-5"
	// webhookPayloadPath is the well-known path where the webhook payload JSON
	// is exposed inside the session container.
	// For non-stock sessions this file is provided by a read-only Kubernetes
	// Secret volume mount.  For stock sessions (pre-warmed pods) the volume is
	// absent; the provisioner writes the file itself from SessionSettings so
	// that both paths behave identically.
)

var runtimeHome = provisionerHome()
var sessionEnvFile = filepath.Join(runtimeHome, ".session", "env")
var claudeMDPath = filepath.Join(runtimeHome, ".claude", "CLAUDE.md")
var workdirRepoPath = envPath("AGENTAPI_REPO_DIR", filepath.Join(runtimeHome, "workdir", "repo"))
var webhookPayloadPath = nativeRuntimePath("webhook", "payload.json", "/opt/webhook/payload.json")
var codexRequirementsPath = nativeRuntimePath("codex", "requirements.toml", "/etc/codex/requirements.toml")
var acpHistoryPath = nativeRuntimePath("acp-posts", "history.jsonl", "/opt/acp-posts/history.jsonl")
var piOllamaCommandPath = filepath.Join(runtimeHome, ".session", "pi-ollama-pi")
var codexSkillsPath = filepath.Join(runtimeHome, ".codex", "skills")
var piSkillsPath = filepath.Join(runtimeHome, ".pi", "agent", "skills")
var piAgentInstructionsPath = filepath.Join(runtimeHome, ".pi", "agent", "AGENTS.md")
var piSettingsPath = filepath.Join(runtimeHome, ".pi", "agent", "settings.json")

func envPath(name, fallback string) string {
	if value := strings.TrimSpace(os.Getenv(name)); value != "" {
		return value
	}
	return fallback
}

func provisionerHome() string {
	if strings.TrimSpace(os.Getenv("AGENTAPI_NATIVE_SESSION_ROOT")) != "" {
		return envPath("HOME", "/home/agentapi")
	}
	return "/home/agentapi"
}

func nativeRuntimePath(parts ...string) string {
	fallback := parts[len(parts)-1]
	parts = parts[:len(parts)-1]
	if root := strings.TrimSpace(os.Getenv("AGENTAPI_NATIVE_SESSION_ROOT")); root != "" {
		pathParts := append([]string{root, "runtime"}, parts...)
		return filepath.Join(pathParts...)
	}
	return fallback
}

func provisionSettingsPath() string {
	return nativeRuntimePath("provision-settings.yaml", filepath.Join(os.TempDir(), fmt.Sprintf("agentapi-provision-settings-%d.yaml", os.Getpid())))
}

func normalizeNativeSettings(settings *sessionsettings.SessionSettings) {
	root := strings.TrimSpace(os.Getenv("AGENTAPI_NATIVE_SESSION_ROOT"))
	if root == "" || settings == nil {
		return
	}
	rewrite := func(path string) string {
		if path == "/home/agentapi" {
			return runtimeHome
		}
		if strings.HasPrefix(path, "/home/agentapi/") {
			return filepath.Join(runtimeHome, strings.TrimPrefix(path, "/home/agentapi/"))
		}
		return path
	}
	if settings.Repository != nil {
		settings.Repository.CloneDir = rewrite(settings.Repository.CloneDir)
		if settings.Repository.CloneDir == "" {
			settings.Repository.CloneDir = workdirRepoPath
		}
	}
	for i := range settings.Files {
		settings.Files[i].Path = rewrite(settings.Files[i].Path)
	}
	for i, path := range settings.UnsyncedFilePaths {
		settings.UnsyncedFilePaths[i] = rewrite(path)
	}
	if settings.Env == nil {
		settings.Env = make(map[string]string)
	}
	settings.Env["HOME"] = runtimeHome
	settings.Env["AGENTAPI_WORKDIR"] = envPath("AGENTAPI_WORKDIR", filepath.Dir(workdirRepoPath))
	settings.Env["AGENTAPI_CLONE_DIR"] = workdirRepoPath
	settings.Env["AGENTAPI_PORT"] = envPath("AGENTAPI_PORT", "8080")
	for _, key := range []string{"HTTP_PROXY", "HTTPS_PROXY", "ALL_PROXY", "http_proxy", "https_proxy", "all_proxy"} {
		if strings.Contains(settings.Env[key], "127.0.0.1:18081") {
			delete(settings.Env, key)
		}
	}
	// These paths are generated by the Kubernetes SCIA sidecar and do not exist
	// on a native host. Leaving one behind breaks Codex/Node TLS initialization.
	for _, key := range []string{
		"SSL_CERT_FILE", "REQUESTS_CA_BUNDLE", "CURL_CA_BUNDLE", "GIT_SSL_CAINFO", "NODE_EXTRA_CA_CERTS",
	} {
		value := settings.Env[key]
		if strings.HasPrefix(value, "/etc/scia/") || strings.HasPrefix(value, "/tmp/scia-") {
			delete(settings.Env, key)
		}
	}
	delete(settings.Env, "AGENTAPI_SCIA_PROXY_URL")
	delete(settings.Env, "AGENTAPI_SCIA_SESSION_SIDECAR_ENABLED")
	settings.OtelCollector = nil
	settings.Sandbox = nil
}

// runProvision executes the full provisioning sequence and then supervises
// the agentapi subprocess.
//
// Sequence:
//  1. Write received settings to a temp YAML file
//  2. Run sessionsettings.Setup() (write-pem, clone-repo, compile, sync-extra)
//  3. Load the generated session env file
//  4. Fetch memory from the proxy and inject into CLAUDE.md
//  5. cd into the cloned repo if present
//  6. Start agentapi (or an ACP bridge) as a subprocess
//  7. Wait for agentapi to become ready
//  8. Send the initial message if specified in settings
//  9. Set status to "ready"; supervise the subprocess
func (s *Server) runProvision(ctx context.Context, settings *sessionsettings.SessionSettings) {
	normalizeNativeSettings(settings)
	startedAt := time.Now()
	s.setPhase("provision:start")
	log.Printf("[PROVISIONER] Starting provisioning for session %s", settings.Session.ID)
	defer func() {
		if ctx.Err() != nil {
			status, msg, phase, elapsed := s.snapshot()
			log.Printf("[PROVISIONER] Provisioning stopped because context was cancelled (session=%s, status=%s, message=%q, phase=%q, phase_elapsed=%s, total_elapsed=%s, err=%v)", settings.Session.ID, status, msg, phase, elapsed.Round(time.Millisecond), time.Since(startedAt).Round(time.Millisecond), ctx.Err())
		}
	}()

	// ── Step 1: write settings to temp YAML ──────────────────────────────────
	s.setPhase("provision:write-settings")
	data, err := sessionsettings.MarshalYAML(settings)
	if err != nil {
		s.setStatus(StatusError, fmt.Sprintf("failed to marshal settings: %v", err))
		return
	}
	provisionTempSettings := provisionSettingsPath()
	if err := os.WriteFile(provisionTempSettings, data, 0o600); err != nil {
		s.setStatus(StatusError, fmt.Sprintf("failed to write temp settings: %v", err))
		return
	}
	defer func() { _ = os.Remove(provisionTempSettings) }()

	// ── Step 1.5: write webhook payload file ─────────────────────────────────
	// For stock sessions the pod is pre-created without a webhook-payload
	// Secret volume (payload unknown at pod creation time).  We write the
	// payload to the well-known path here so that /opt/webhook/payload.json is
	// available to the agent regardless of whether the session was fulfilled
	// from the stock inventory or from a freshly created pod.
	// For non-stock sessions the file already exists (read-only Secret volume
	// mount), so writeWebhookPayloadFile is a no-op in that case.
	s.setPhase("provision:write-webhook-payload")
	if settings.WebhookPayload != "" {
		writeWebhookPayloadFile(settings.WebhookPayload)
	}

	// ── Step 2: run setup ─────────────────────────────────────────────────────
	// Override CompileOptions.InputPath to use the temp file written above,
	// not the default /session-settings/settings.yaml (which is no longer mounted).
	compileOpts := sessionsettings.DefaultCompileOptions()
	compileOpts.InputPath = provisionTempSettings

	opts := sessionsettings.SetupOptions{
		InputPath:                 provisionTempSettings,
		CompileOptions:            compileOpts,
		NotificationSubscriptions: nativeRuntimePath("notification-subscriptions-source", "/notification-subscriptions-source"),
		NotificationsDir:          filepath.Join(runtimeHome, "notifications"),
		RegisterMarketplaces:      true,
	}
	s.setPhase("provision:session-setup")
	log.Printf("[PROVISIONER] Running session setup")
	if err := sessionsettings.Setup(opts); err != nil {
		s.setStatus(StatusError, fmt.Sprintf("setup failed: %v", err))
		return
	}
	log.Printf("[PROVISIONER] Session setup complete")

	// ── Step 2.3: docker login for DinD registries ───────────────────────────
	s.setPhase("provision:post-setup")
	if settings.Docker != nil && settings.Docker.Enabled {
		go s.runDockerLogins(ctx, settings.Docker)
	}

	// ── Step 2.5: restore managed files from provision payload ───────────────
	// Files are embedded in SessionSettings.Files by the proxy at session creation
	// time (read from agentapi-agent-files-{userID} Secret).
	// Write each file to its path so agents can use them immediately.
	if len(settings.Files) > 0 {
		if err := writeFiles(settings.Files); err != nil {
			log.Printf("[PROVISIONER] Warning: failed to write managed files: %v", err)
		}
		// Re-apply compiled hooks into settings.json in case a managed settings.json
		// overwrote the hooks that were generated during the compile step above.
		// This preserves user customisations while ensuring oneshot/cycle/managed
		// hooks injected by the proxy are always present.
		if settings.Claude.SettingsJSON != nil {
			claudeSettingsPath := filepath.Join(compileOpts.OutputDir, ".claude", "settings.json")
			if err := mergeHooksIntoSettingsFile(claudeSettingsPath, settings.Claude.SettingsJSON); err != nil {
				log.Printf("[PROVISIONER] Warning: failed to re-apply hooks to settings.json: %v", err)
			}
		}
	} else if settings.Credentials != "" {
		// Backward compat: old sessions only have Credentials (= ~/.codex/auth.json).
		if err := writeCredentials(settings.Credentials); err != nil {
			log.Printf("[PROVISIONER] Warning: failed to write credentials (legacy): %v", err)
		} else {
			log.Printf("[PROVISIONER] Restored credentials to ~/.codex/auth.json (legacy)")
		}
	}

	// ── Step 2.6: expose Codex skills to Pi ─────────────────────────────────
	// sessionsettings.Setup syncs marketplace skills into ~/.codex/skills. Pi
	// discovers global skills from ~/.pi/agent/skills, so link that path to the
	// Codex skills directory before the ACP bridge starts Pi.
	if err := symlinkCodexSkillsForPi(codexSkillsPath, piSkillsPath); err != nil {
		log.Printf("[PROVISIONER] Warning: failed to link Codex skills for Pi: %v", err)
	}

	// ── Step 2.7: write managed Codex requirements ─────────────────────────
	// Codex only auto-trusts hooks from the managed requirements layer.  The
	// user-layer ~/.codex/hooks.json is still generated for visibility, but
	// /etc/codex/requirements.toml is what makes hooks run without approval.
	if err := writeCodexRequirements(settings.Codex.HooksJSON); err != nil {
		log.Printf("[PROVISIONER] Warning: failed to write Codex managed requirements: %v", err)
	}

	// ── Step 3: load session env file ─────────────────────────────────────────
	s.setPhase("provision:load-env")
	envMap := loadEnvFile(sessionEnvFile)
	log.Printf("[PROVISIONER] Loaded %d env vars from session env file", len(envMap))
	prepareSciaCABundle(ctx, envMap)

	// ── Step 4: fetch memory from proxy → inject into CLAUDE.md ──────────────
	s.setPhase("provision:fetch-memory")
	s.fetchAndInjectMemory(envMap)

	// ── Step 4.5: expose managed instructions and MCP servers to Pi ──────────
	s.setPhase("provision:write-agent-files")
	if err := writePiAgentInstructions(claudeMDPath, piAgentInstructionsPath); err != nil {
		log.Printf("[PROVISIONER] Warning: failed to write Pi AGENTS.md: %v", err)
	}
	if err := writePiMCPServers(piSettingsPath, piMCPServers(settings)); err != nil {
		log.Printf("[PROVISIONER] Warning: failed to write Pi MCP settings: %v", err)
	}

	// ── Step 5: cd into cloned repo ───────────────────────────────────────────
	s.setPhase("provision:chdir")
	if _, err := os.Stat(workdirRepoPath); err == nil {
		log.Printf("[PROVISIONER] Changing to repo directory %s", workdirRepoPath)
		if err := os.Chdir(workdirRepoPath); err != nil {
			log.Printf("[PROVISIONER] Warning: failed to chdir to %s: %v", workdirRepoPath, err)
		}
	}
	if os.Getenv("AGENTAPI_NATIVE_SESSION_ROOT") != "" {
		if cwd, err := os.Getwd(); err == nil {
			if err := trustNativeWorkspace(filepath.Join(runtimeHome, ".claude.json"), cwd); err != nil {
				log.Printf("[PROVISIONER] Warning: failed to mark native workspace trusted: %v", err)
			}
		}
	}

	// ── Step 5.5: run pre-script ─────────────────────────────────────────────
	// Executes the optional shell pre-script before starting the agent.
	// Pre-scripts are used for setup tasks such as pre-fetching npm/bun packages.
	// Failure is non-fatal: a warning is logged and provisioning continues.
	if settings.Startup.PreScript != "" {
		s.setPhase("provision:pre-script")
		log.Printf("[PROVISIONER] Running pre-script")
		if err := s.runPreScript(ctx, settings.Startup.PreScript, envMap); err != nil {
			log.Printf("[PROVISIONER] Warning: pre-script failed (continuing): %v", err)
		} else {
			log.Printf("[PROVISIONER] Pre-script complete")
		}
	}

	// ── Step 6: start otelcol subprocess if in-process mode ──────────────────
	// Must be started before agentapi so metrics scraping begins as soon as
	// Claude Code starts emitting metrics on its prometheus port.
	if settings.OtelCollector != nil && settings.OtelCollector.Enabled {
		go s.runOtelcol(ctx, settings.OtelCollector)
	}

	// ── Step 7: build and start the agent subprocess ──────────────────────────
	s.setPhase("provision:start-agent")
	agentCmd, agentArgs := s.buildAgentCommand(settings, envMap)
	log.Printf("[PROVISIONER] Starting agent: %s %v", agentCmd, agentArgs)

	cmd := exec.CommandContext(ctx, agentCmd, agentArgs...)
	cmd.Env = mergeEnv(os.Environ(), envMap)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr

	if err := cmd.Start(); err != nil {
		s.setStatus(StatusError, fmt.Sprintf("failed to start agent: %v", err))
		return
	}
	log.Printf("[PROVISIONER] Agent process started (pid %d)", cmd.Process.Pid)

	// ── Step 8: wait for agentapi to be ready ─────────────────────────────────
	s.setPhase("provision:wait-agentapi-ready")
	agentapiPort := os.Getenv("AGENTAPI_PORT")
	if agentapiPort == "" {
		agentapiPort = "8080"
	}
	agentapiURL := fmt.Sprintf("http://localhost:%s", agentapiPort)

	log.Printf("[PROVISIONER] Waiting for agentapi to be ready at %s", agentapiURL)
	if err := waitForAgentAPI(ctx, agentapiURL, 120); err != nil {
		s.setStatus(StatusError, fmt.Sprintf("agentapi not ready: %v", err))
		_ = cmd.Process.Kill()
		return
	}
	log.Printf("[PROVISIONER] agentapi is ready")

	// Enable the network-filter policy now that the agent is fully started.
	// This is a best-effort call; if there is no sandbox sidecar the request
	// simply fails and is ignored.
	configureNetworkFilterPolicy(settings.Sandbox)
	enableNetworkFilterPolicy()

	// ── Step 9: send initial message ─────────────────────────────────────────
	if settings.InitialMessage != "" {
		s.setPhase("provision:send-initial-message")
		log.Printf("[PROVISIONER] Sending initial message")
		agentType := settings.Session.AgentType
		waitSec := 2
		if v := os.Getenv("INITIAL_MESSAGE_WAIT_SECOND"); v != "" {
			if _, err := fmt.Sscanf(v, "%d", &waitSec); err != nil {
				log.Printf("[PROVISIONER] Warning: invalid INITIAL_MESSAGE_WAIT_SECOND=%q: %v", v, err)
			}
		}
		sendInitialMessage(ctx, agentapiURL, settings.InitialMessage, agentType, waitSec)
	}

	// ── Step 10: mark ready and supervise ────────────────────────────────────
	s.setPhase("provision:ready")
	s.setStatus(StatusReady, "")

	// ── Step 11: launch acp-posts subprocess if SlackParams provided ─────────
	if settings.SlackParams != nil && settings.SlackParams.Channel != "" {
		go s.runAcpPosts(ctx, settings.SlackParams, settings.Session.AgentType)
	}

	// ── Step 12: start files sync goroutine ───────────────────────────────────
	// Syncs managedFilePaths → Kubernetes Secret agentapi-agent-files-{userID}.
	// Runs in-process instead of as a sidecar so that UserID is always set
	// (stock pool pods have empty UserID at pod creation time).
	go s.runFilesSync(ctx, settings.Session.UserID, settings.UnsyncedFilePaths)

	// Supervise: if agentapi exits, report error so K8s restarts the Pod.
	go func() {
		if err := cmd.Wait(); err != nil {
			s.setStatus(StatusError, fmt.Sprintf("agent process exited: %v", err))
		} else {
			s.setStatus(StatusError, "agent process exited with code 0")
		}
	}()
}

func trustNativeWorkspace(configPath, workspace string) error {
	data, err := os.ReadFile(configPath)
	if err != nil && !os.IsNotExist(err) {
		return err
	}
	config := make(map[string]interface{})
	if len(data) > 0 {
		if err := json.Unmarshal(data, &config); err != nil {
			return err
		}
	}
	projects, _ := config["projects"].(map[string]interface{})
	if projects == nil {
		projects = make(map[string]interface{})
	}
	project, _ := projects[workspace].(map[string]interface{})
	if project == nil {
		project = make(map[string]interface{})
	}
	project["hasTrustDialogAccepted"] = true
	project["hasCompletedProjectOnboarding"] = true
	projects[workspace] = project
	config["projects"] = projects
	out, err := json.MarshalIndent(config, "", "  ")
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(configPath), 0o700); err != nil {
		return err
	}
	return os.WriteFile(configPath, out, 0o600)
}

// runDockerLogins runs in the background after DinD is enabled: waits for the docker daemon
// to be ready, then runs docker login for each registry with inline credentials.
// Secret-based registries are already mounted as /root/.docker/config.json in the DinD
// container, so they need no docker login call here.
func (s *Server) runDockerLogins(ctx context.Context, docker *sessionsettings.DockerConfig) {
	if docker == nil || !docker.Enabled {
		return
	}

	// Check if there are any inline credentials to log in with.
	hasInlineCreds := false
	for _, reg := range docker.Registries {
		if reg.Username != "" && reg.Password != "" {
			hasInlineCreds = true
			break
		}
	}
	if !hasInlineCreds {
		return
	}

	// Wait for the DinD daemon to be ready (up to 120 seconds).
	log.Printf("[PROVISIONER] Waiting for Docker daemon to be ready")
	deadline := time.Now().Add(120 * time.Second)
	for time.Now().Before(deadline) {
		cmd := exec.CommandContext(ctx, "docker", "info")
		if err := cmd.Run(); err == nil {
			break
		}
		select {
		case <-ctx.Done():
			log.Printf("[PROVISIONER] Context cancelled while waiting for Docker daemon")
			return
		case <-time.After(2 * time.Second):
		}
	}
	log.Printf("[PROVISIONER] Docker daemon is ready")

	// Run docker login for each registry with inline credentials.
	for _, reg := range docker.Registries {
		if reg.Username == "" || reg.Password == "" {
			continue
		}
		log.Printf("[PROVISIONER] Logging into registry %s as %s", reg.Server, reg.Username)
		args := []string{"login", "-u", reg.Username, "--password-stdin"}
		if reg.Server != "" {
			args = append(args, reg.Server)
		}
		cmd := exec.CommandContext(ctx, "docker", args...)
		cmd.Stdin = strings.NewReader(reg.Password)
		cmd.Stdout = os.Stdout
		cmd.Stderr = os.Stderr
		if err := cmd.Run(); err != nil {
			log.Printf("[PROVISIONER] Warning: docker login for %s failed: %v", reg.Server, err)
		} else {
			log.Printf("[PROVISIONER] Successfully logged into registry %s", reg.Server)
		}
	}
}

// runPreScript executes the pre-script shell snippet before the agent process starts.
// It inherits the session environment and streams stdout/stderr to the provisioner log.
func (s *Server) runPreScript(ctx context.Context, script string, envMap map[string]string) error {
	cmd := exec.CommandContext(ctx, "sh", "-c", script)
	cmd.Env = mergeEnv(os.Environ(), envMap)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	return cmd.Run()
}

// runAcpPosts starts the acp-posts binary as a subprocess, forwarding
// agent output (history.jsonl) to Slack. It waits for the ACP bridge history
// file to appear before launching.
//
// The subprocess is tied to ctx: when ctx is cancelled the goroutine exits.
func (s *Server) runAcpPosts(ctx context.Context, params *sessionsettings.SlackParams, agentType string) {
	const acpPostsBin = "/usr/local/bin/acp-posts"

	historyFile := acpHistoryPath

	log.Printf("[ACP_POSTS] Waiting for history file %s", historyFile)
	for {
		select {
		case <-ctx.Done():
			log.Printf("[ACP_POSTS] Context cancelled while waiting for history file")
			return
		case <-time.After(time.Second):
		}
		if _, err := os.Stat(historyFile); err == nil {
			break
		}
	}
	log.Printf("[ACP_POSTS] History file found, starting acp-posts")

	cmd := exec.CommandContext(ctx, acpPostsBin, "--file", historyFile)
	cmd.Env = append(os.Environ(),
		"SLACK_BOT_TOKEN="+params.BotToken,
		"SLACK_CHANNEL_ID="+params.Channel,
		"SLACK_THREAD_TS="+params.ThreadTS,
	)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr

	if err := cmd.Run(); err != nil {
		// ctx cancellation causes an expected error; don't log it as fatal.
		if ctx.Err() != nil {
			log.Printf("[ACP_POSTS] Exited due to context cancellation")
		} else {
			log.Printf("[ACP_POSTS] Exited with error: %v", err)
		}
	} else {
		log.Printf("[ACP_POSTS] Exited normally")
	}
}

// managedFilePaths lists the absolute paths that runFilesSync watches and persists
// to the agentapi-agent-files-{userID} Secret.  Order determines the index used as
// the Secret key prefix (0, 1, …).
var managedFilePaths = []string{
	filepath.Join(runtimeHome, ".codex", "auth.json"),
	filepath.Join(runtimeHome, ".claude", ".credentials.json"),
}

// writeFiles writes each ManagedFile to its path, creating parent directories
// as needed.  The file mode is taken from ManagedFile.Permissions (octal string,
// e.g. "0600"); if empty or unparseable, 0600 is used as a safe default.
// Called once at provision time to restore files delivered via SessionSettings.
func writeFiles(files []sessionsettings.ManagedFile) error {
	var firstErr error
	for _, f := range files {
		perm := os.FileMode(0600)
		if f.Permissions != "" {
			if p, err := strconv.ParseUint(f.Permissions, 8, 32); err == nil {
				perm = os.FileMode(p)
			} else {
				log.Printf("[PROVISIONER] Warning: invalid permissions %q for %s, using 0600", f.Permissions, f.Path)
			}
		}
		if err := os.MkdirAll(filepath.Dir(f.Path), 0755); err != nil {
			log.Printf("[PROVISIONER] Warning: failed to create dir for %s: %v", f.Path, err)
			if firstErr == nil {
				firstErr = err
			}
			continue
		}
		if err := os.WriteFile(f.Path, []byte(f.Content), perm); err != nil {
			log.Printf("[PROVISIONER] Warning: failed to write %s: %v", f.Path, err)
			if firstErr == nil {
				firstErr = err
			}
			continue
		}
		log.Printf("[PROVISIONER] Restored managed file: %s (mode %s)", f.Path, perm)
	}
	return firstErr
}

func writeCodexRequirements(hooksJSON map[string]interface{}) error {
	if len(hooksJSON) == 0 {
		return nil
	}

	content, err := buildCodexRequirementsTOML(sessionsettings.MergeCodexManagedHooks(hooksJSON))
	if err != nil {
		return err
	}
	if strings.TrimSpace(content) == "" {
		return nil
	}
	return writeCodexRequirementsToPath(codexRequirementsPath, content)
}

func writeCodexRequirementsToPath(path, content string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return fmt.Errorf("failed to create %s: %w", filepath.Dir(path), err)
	}
	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		return fmt.Errorf("failed to write %s: %w", path, err)
	}
	log.Printf("[PROVISIONER] Wrote Codex managed requirements to %s", path)
	return nil
}

func buildCodexRequirementsTOML(hooksJSON map[string]interface{}) (string, error) {
	rawHooks, ok := hooksJSON["hooks"]
	if !ok {
		return "", nil
	}
	hooksMap, ok := rawHooks.(map[string]interface{})
	if !ok || len(hooksMap) == 0 {
		return "", nil
	}

	var events []string
	for event := range hooksMap {
		// Codex does not support Claude Code's Notification hook event.
		if event == "Notification" {
			continue
		}
		entries := asInterfaceSlice(hooksMap[event])
		if len(entries) == 0 {
			continue
		}
		events = append(events, event)
	}
	sort.Strings(events)
	if len(events) == 0 {
		return "", nil
	}

	var b strings.Builder
	b.WriteString("[hooks]\n")
	b.WriteString("managed_dir = \"/etc/codex\"\n")

	for _, event := range events {
		entries := asInterfaceSlice(hooksMap[event])
		for _, entry := range entries {
			entryMap := asStringMap(entry)
			if len(entryMap) == 0 {
				continue
			}
			hookEntries := asInterfaceSlice(entryMap["hooks"])
			if len(hookEntries) == 0 {
				continue
			}

			b.WriteString("\n")
			b.WriteString("[[hooks.")
			b.WriteString(event)
			b.WriteString("]]\n")

			for _, hook := range hookEntries {
				hookMap := asStringMap(hook)
				if len(hookMap) == 0 {
					continue
				}
				hookType, _ := hookMap["type"].(string)
				command, _ := hookMap["command"].(string)
				if hookType == "" || command == "" {
					continue
				}
				b.WriteString("\n")
				b.WriteString("[[hooks.")
				b.WriteString(event)
				b.WriteString(".hooks]]\n")
				b.WriteString("type = ")
				b.WriteString(tomlQuote(hookType))
				b.WriteString("\n")
				b.WriteString("command = ")
				b.WriteString(tomlQuote(command))
				b.WriteString("\n")
			}
		}
	}

	return b.String(), nil
}

func asInterfaceSlice(v interface{}) []interface{} {
	switch typed := v.(type) {
	case []interface{}:
		return typed
	case []map[string]interface{}:
		out := make([]interface{}, 0, len(typed))
		for _, item := range typed {
			out = append(out, item)
		}
		return out
	default:
		return nil
	}
}

func asStringMap(v interface{}) map[string]interface{} {
	if typed, ok := v.(map[string]interface{}); ok {
		return typed
	}
	return nil
}

func tomlQuote(s string) string {
	return strconv.Quote(s)
}

// mergeHooksIntoSettingsFile reads the Claude Code settings.json at path, merges
// any hooks from compiledSettings into it (compiled hooks win per event name),
// and writes the result back.  This ensures that proxy-injected hooks (oneshot
// delete-session, cycle, etc.) survive even when a managed settings.json file
// was restored on top of the compiled one.
func mergeHooksIntoSettingsFile(path string, compiledSettings map[string]interface{}) error {
	compiledHooksRaw, ok := compiledSettings["hooks"]
	if !ok {
		return nil // no hooks to inject
	}
	compiledHooks, ok := compiledHooksRaw.(map[string]interface{})
	if !ok || len(compiledHooks) == 0 {
		return nil
	}

	// Read the current file (may have been overwritten by writeFiles)
	data, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("read: %w", err)
	}

	var current map[string]interface{}
	if err := json.Unmarshal(data, &current); err != nil {
		return fmt.Errorf("parse: %w", err)
	}

	// Merge: start with whatever hooks the managed file already has, then
	// overwrite per-event with the compiled hooks so proxy-injected entries win.
	merged := make(map[string]interface{})
	if existingRaw, ok := current["hooks"]; ok {
		if existing, ok := existingRaw.(map[string]interface{}); ok {
			for k, v := range existing {
				merged[k] = v
			}
		}
	}
	for k, v := range compiledHooks {
		merged[k] = v
	}
	current["hooks"] = merged

	out, err := json.MarshalIndent(current, "", "  ")
	if err != nil {
		return fmt.Errorf("marshal: %w", err)
	}
	if err := os.WriteFile(path, out, 0644); err != nil {
		return fmt.Errorf("write: %w", err)
	}
	log.Printf("[PROVISIONER] Re-applied compiled hooks to %s", path)
	return nil
}

// writeCredentials writes the given JSON string to ~/.codex/auth.json (mode 0600).
// Deprecated: used only for backward compatibility with old SessionSettings that
// do not have the Files field.  New sessions use writeFiles instead.
func writeCredentials(credentialsJSON string) error {
	codexDir := filepath.Join(os.Getenv("HOME"), ".codex")
	if codexDir == "/.codex" {
		codexDir = "/home/agentapi/.codex"
	}
	if err := os.MkdirAll(codexDir, 0755); err != nil {
		return fmt.Errorf("failed to create .codex directory: %w", err)
	}
	destPath := filepath.Join(codexDir, "auth.json")
	if err := os.WriteFile(destPath, []byte(credentialsJSON), 0600); err != nil {
		return fmt.Errorf("failed to write auth.json: %w", err)
	}
	return nil
}

// runFilesSync watches the paths listed in managedFilePaths for changes and syncs
// all of them to the Kubernetes Secret agentapi-agent-files-{userID} using the
// in-cluster k8s client.
// The goroutine is tied to ctx: when ctx is cancelled the loop exits.
func (s *Server) runFilesSync(ctx context.Context, userID string, unsyncedFilePaths []string) {
	const syncInterval = 10 * time.Second

	if userID == "" {
		log.Printf("[FILES_SYNC] No user ID set, skipping files sync")
		return
	}

	secretName := "agentapi-agent-files-" + sanitizeCredentialSecretName(userID)

	// Read namespace from the in-cluster service-account namespace file.
	nsBytes, err := os.ReadFile("/var/run/secrets/kubernetes.io/serviceaccount/namespace")
	if err != nil {
		log.Printf("[FILES_SYNC] Not running in a k8s cluster (namespace file not found): %v, skipping", err)
		return
	}
	namespace := strings.TrimSpace(string(nsBytes))

	watchedPaths := syncedManagedFilePaths(unsyncedFilePaths)
	if len(watchedPaths) == 0 {
		log.Printf("[FILES_SYNC] No managed file paths left after exclusions %v, skipping files sync", unsyncedFilePaths)
		return
	}

	log.Printf("[FILES_SYNC] Starting: watching %v -> Secret %s/%s (interval: %s)", watchedPaths, namespace, secretName, syncInterval)

	k8sCfg, err := rest.InClusterConfig()
	if err != nil {
		log.Printf("[FILES_SYNC] Failed to get in-cluster config: %v, skipping", err)
		return
	}
	clientset, err := kubernetes.NewForConfig(k8sCfg)
	if err != nil {
		log.Printf("[FILES_SYNC] Failed to create k8s client: %v, skipping", err)
		return
	}

	// Track last hash per file path to detect changes.
	lastHashes := make(map[string]string, len(watchedPaths))

	ticker := time.NewTicker(syncInterval)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			log.Printf("[FILES_SYNC] Context cancelled, stopping")
			return
		case <-ticker.C:
			// Read each file exactly once to avoid TOCTOU races between the
			// hash-check pass and the content-collection pass.
			type fileSnapshot struct {
				data []byte
				hash string
			}
			snapshots := make(map[string]fileSnapshot, len(watchedPaths))
			for _, path := range watchedPaths {
				data, hash, err := readFileWithHash(path)
				if err != nil {
					// File may not exist yet; not an error.
					continue
				}
				snapshots[path] = fileSnapshot{data: data, hash: hash}
			}

			changed := false
			for _, path := range watchedPaths {
				snap, ok := snapshots[path]
				if !ok {
					continue
				}
				if snap.hash != lastHashes[path] {
					changed = true
				}
			}
			if !changed {
				continue
			}

			// Build the full snapshot of all managed files from the single read above.
			files := make([]sessionsettings.ManagedFile, 0, len(snapshots))
			for _, path := range watchedPaths {
				snap, ok := snapshots[path]
				if !ok {
					continue
				}
				files = append(files, sessionsettings.ManagedFile{
					Path:    path,
					Content: string(snap.data),
				})
			}

			secretData := sessionsettings.FilesToSecretData(files)
			log.Printf("[FILES_SYNC] Files changed, syncing %d file(s) to Secret %s", len(files), secretName)
			if err := upsertFilesSecret(ctx, clientset, namespace, secretName, secretData); err != nil {
				log.Printf("[FILES_SYNC] ERROR: failed to upsert Secret: %v", err)
				// Do not update lastHashes so the next tick retries the sync.
			} else {
				log.Printf("[FILES_SYNC] Successfully synced to Secret %s", secretName)
				// Update hashes only after a successful sync so failed upserts are retried.
				for _, path := range watchedPaths {
					if snap, ok := snapshots[path]; ok {
						lastHashes[path] = snap.hash
					}
				}
			}
		}
	}
}

func syncedManagedFilePaths(unsyncedFilePaths []string) []string {
	excluded := make(map[string]struct{}, len(unsyncedFilePaths))
	for _, path := range unsyncedFilePaths {
		path = strings.TrimSpace(path)
		if path == "" {
			continue
		}
		excluded[path] = struct{}{}
	}

	paths := make([]string, 0, len(managedFilePaths))
	for _, path := range managedFilePaths {
		if _, ok := excluded[path]; ok {
			continue
		}
		paths = append(paths, path)
	}
	return paths
}

// readFileWithHash reads a file and returns its content and hex-encoded SHA256 hash.
func readFileWithHash(path string) ([]byte, string, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, "", err
	}
	sum := sha256.Sum256(data)
	return data, fmt.Sprintf("%x", sum), nil
}

// upsertFilesSecret creates or updates the agentapi-agent-files-{userID} Kubernetes
// Secret with the provided index-based file data produced by FilesToSecretData.
func upsertFilesSecret(ctx context.Context, clientset kubernetes.Interface, namespace, name string, data map[string][]byte) error {
	secret := &corev1.Secret{
		ObjectMeta: metav1.ObjectMeta{
			Name:      name,
			Namespace: namespace,
			Labels: map[string]string{
				"app.kubernetes.io/name":       "agentapi-agent-files",
				"app.kubernetes.io/managed-by": "agentapi-proxy",
			},
		},
		Type: corev1.SecretTypeOpaque,
		Data: data,
	}

	_, err := clientset.CoreV1().Secrets(namespace).Create(ctx, secret, metav1.CreateOptions{})
	if err == nil {
		return nil
	}
	if k8serrors.IsAlreadyExists(err) {
		_, err = clientset.CoreV1().Secrets(namespace).Update(ctx, secret, metav1.UpdateOptions{})
		return err
	}
	return err
}

// sanitizeCredentialSecretName converts a userID into a valid Kubernetes Secret
// name component (lowercase alphanumeric and dashes only, max 50 chars).
func sanitizeCredentialSecretName(s string) string {
	s = strings.ToLower(s)
	re := regexp.MustCompile(`[^a-z0-9-]`)
	s = re.ReplaceAllString(s, "-")
	s = strings.Trim(s, "-")
	if len(s) > 50 {
		s = s[:50]
	}
	return s
}

// runOtelcol starts the OpenTelemetry Collector binary as a subprocess.
// It is used when otelcol runs in in-process mode (OtelCollectorInProcess=true)
// instead of as a Kubernetes sidecar. This allows otelcol to be started
// after user context is established, so metrics labels (user_id, session_id,
// etc.) are correctly set even when using the stock inventory feature.
// The subprocess is tied to ctx: when ctx is cancelled the goroutine exits.
func (s *Server) runOtelcol(ctx context.Context, cfg *sessionsettings.OtelCollectorConfig) {
	const otelcolBin = "/usr/local/bin/otelcol"
	const configPath = "/tmp/otelcol-config.yaml"

	scrapeInterval := cfg.ScrapeInterval
	if scrapeInterval == "" {
		scrapeInterval = "15s"
	}
	claudeCodePort := cfg.ClaudeCodePort
	if claudeCodePort == 0 {
		claudeCodePort = 9464
	}
	exporterPort := cfg.ExporterPort
	if exporterPort == 0 {
		exporterPort = 9090
	}

	// Generate otelcol config with label values already substituted.
	// Using Go fmt.Sprintf rather than otelcol ${env:VAR} expansion so that
	// the correct values are used regardless of the container's own env vars
	// (which may be unset in stock sessions at startup time).
	otelConfig := fmt.Sprintf(`receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'claude-code'
          scrape_interval: %s
          static_configs:
            - targets: ['localhost:%d']

processors:
  resource:
    attributes:
      - key: user_id
        action: delete
      - key: session_id
        action: delete
  transform:
    error_mode: ignore
    metric_statements:
      - context: datapoint
        statements:
          # Rename claude-code's native labels
          - set(attributes["claude_user_id"], attributes["user_id"]) where attributes["user_id"] != nil
          - set(attributes["claude_session_id"], attributes["session_id"]) where attributes["session_id"] != nil
          - delete_key(attributes, "user_id")
          - delete_key(attributes, "session_id")
          # Remove user_email label to prevent it from being scraped by Prometheus
          - delete_key(attributes, "user_email")
          # Add agentapi labels
          - set(attributes["agentapi_session_id"], "%s")
          - set(attributes["agentapi_user_id"], "%s")
          - set(attributes["agentapi_team_id"], "%s")
          - set(attributes["agentapi_schedule_id"], "%s")
          - set(attributes["agentapi_webhook_id"], "%s")
          - set(attributes["agentapi_agent_type"], "%s")

exporters:
  prometheus:
    endpoint: "0.0.0.0:%d"
    resource_to_telemetry_conversion:
      enabled: false

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: [resource, transform]
      exporters: [prometheus]`,
		scrapeInterval, claudeCodePort,
		cfg.SessionID, cfg.UserID, cfg.TeamID,
		cfg.ScheduleID, cfg.WebhookID, cfg.AgentType,
		exporterPort)

	if err := os.WriteFile(configPath, []byte(otelConfig), 0o600); err != nil {
		log.Printf("[OTELCOL] Failed to write config to %s: %v", configPath, err)
		return
	}
	log.Printf("[OTELCOL] Config written to %s, starting otelcol subprocess", configPath)

	cmd := exec.CommandContext(ctx, otelcolBin, "--config="+configPath)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr

	if err := cmd.Run(); err != nil {
		if ctx.Err() != nil {
			log.Printf("[OTELCOL] Exited due to context cancellation")
		} else {
			log.Printf("[OTELCOL] Exited with error: %v", err)
		}
	} else {
		log.Printf("[OTELCOL] Exited normally")
	}
}

// buildAgentCommand returns the executable and arguments for the agent
// process, mirroring the logic in BuildRemoteProvisionSettings().
func (s *Server) buildAgentCommand(settings *sessionsettings.SessionSettings, envMap map[string]string) (string, []string) {
	agentType := settings.Session.AgentType

	agentapiPort := os.Getenv("AGENTAPI_PORT")
	if agentapiPort == "" {
		agentapiPort = "8080"
	}

	switch agentType {
	case "claude-acp":
		// Start the acp-server bridge that wraps claude-agent-acp (ACP agent) via stdio.
		// The bridge exposes an agentapi-compatible HTTP server on AGENTAPI_PORT.
		// --output-file writes conversation history in acp-posts JSONL format for Slack integration.
		// claude-agent-acp is the official ACP adapter for the Claude Agent SDK:
		// https://github.com/agentclientprotocol/claude-agent-acp
		return "agentapi-proxy", []string{
			"acp-server",
			"--port", agentapiPort,
			"--output-file", acpHistoryPath,
			"--",
			"bunx", "@agentclientprotocol/claude-agent-acp",
		}

	case "codex-acp":
		// Start the acp-server bridge that wraps codex-acp (ACP adapter for OpenAI Codex) via stdio.
		// https://github.com/agentclientprotocol/codex-acp
		// --auto-approve bypasses the UI permission modal at the ACP bridge layer.
		return "agentapi-proxy", []string{
			"acp-server",
			"--port", agentapiPort,
			"--auto-approve",
			"--",
			"npx", "-y", "@agentclientprotocol/codex-acp",
		}

	case "pi-ollama":
		// Start the acp-server bridge that wraps pi-acp via stdio. pi-acp starts
		// `pi --mode rpc`; the image/pre-script install pi-ollama-cloud so Pi can
		// talk directly to Ollama Cloud without a local Ollama daemon.
		// https://github.com/svkozak/pi-acp
		ensurePiOllamaEnv(envMap)
		return "agentapi-proxy", []string{
			"acp-server",
			"--port", agentapiPort,
			"--auto-approve",
			"--",
			"npx", "-y", "pi-acp",
		}

	case "cursor":
		// Start the acp-server bridge that wraps Cursor Agent CLI's native ACP server via stdio.
		// https://cursor.com/docs/cli/acp
		// --auto-approve bypasses the UI permission modal at the ACP bridge layer.
		return "agentapi-proxy", []string{
			"acp-server",
			"--port", agentapiPort,
			"--auto-approve",
			"--raw-json-log",
			"--",
			"agent", "acp",
		}

	default:
		// Default: agentapi server wrapping claude
		claudeCmd := "claude"
		if claudeArgs := os.Getenv("CLAUDE_ARGS"); claudeArgs != "" {
			claudeCmd = claudeCmd + " " + claudeArgs
		}
		return "agentapi", []string{
			"server",
			"--allowed-hosts", "*",
			"--allowed-origins", "*",
			"--port", agentapiPort,
			"--",
			"sh", "-c", claudeCmd,
		}
	}
}

func ensurePiOllamaEnv(envMap map[string]string) {
	if envMap == nil {
		return
	}
	if strings.TrimSpace(envMap["PI_ACP_PI_COMMAND"]) == "" {
		envMap["PI_ACP_PI_COMMAND"] = piOllamaCommandPath
	}
	if envMap["PI_ACP_PI_COMMAND"] == piOllamaCommandPath {
		if err := writePiOllamaCommandWrapper(piOllamaCommandPath); err != nil {
			log.Printf("[PROVISIONER] Warning: failed to write pi-ollama command wrapper: %v", err)
		}
	}
}

func writePiOllamaCommandWrapper(path string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	const script = `#!/bin/sh
set -e
model="${PI_OLLAMA_MODEL:-${OLLAMA_MODEL:-` + piOllamaDefaultModel + `}}"
case "$model" in
  */*) exec pi --model "$model" "$@" ;;
  *) exec pi --provider ollama-cloud --model "$model" "$@" ;;
esac
`
	if err := os.WriteFile(path, []byte(script), 0o755); err != nil {
		return err
	}
	return os.Chmod(path, 0o755)
}

func symlinkCodexSkillsForPi(codexPath, piPath string) error {
	if strings.TrimSpace(codexPath) == "" || strings.TrimSpace(piPath) == "" {
		return fmt.Errorf("codex and pi skills paths must be set")
	}
	if err := os.MkdirAll(codexPath, 0o755); err != nil {
		return fmt.Errorf("create codex skills dir: %w", err)
	}
	if err := os.MkdirAll(filepath.Dir(piPath), 0o755); err != nil {
		return fmt.Errorf("create pi skills parent: %w", err)
	}

	info, err := os.Lstat(piPath)
	if err != nil {
		if os.IsNotExist(err) {
			return os.Symlink(codexPath, piPath)
		}
		return fmt.Errorf("stat pi skills path: %w", err)
	}

	if info.Mode()&os.ModeSymlink != 0 {
		target, err := os.Readlink(piPath)
		if err != nil {
			return fmt.Errorf("read pi skills symlink: %w", err)
		}
		if target == codexPath {
			return nil
		}
		if err := os.Remove(piPath); err != nil {
			return fmt.Errorf("remove stale pi skills symlink: %w", err)
		}
		return os.Symlink(codexPath, piPath)
	}

	if info.IsDir() {
		entries, err := os.ReadDir(piPath)
		if err != nil {
			return fmt.Errorf("read existing pi skills dir: %w", err)
		}
		if len(entries) == 0 {
			if err := os.Remove(piPath); err != nil {
				return fmt.Errorf("remove empty pi skills dir: %w", err)
			}
			return os.Symlink(codexPath, piPath)
		}
		return fmt.Errorf("pi skills path already exists and is not empty: %s", piPath)
	}

	return fmt.Errorf("pi skills path already exists and is not a directory or symlink: %s", piPath)
}

func writePiAgentInstructions(sourcePath, destPath string) error {
	if strings.TrimSpace(sourcePath) == "" || strings.TrimSpace(destPath) == "" {
		return fmt.Errorf("source and destination paths must be set")
	}
	content, err := os.ReadFile(sourcePath)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return fmt.Errorf("read source instructions: %w", err)
	}
	if err := os.MkdirAll(filepath.Dir(destPath), 0o755); err != nil {
		return fmt.Errorf("create Pi agent dir: %w", err)
	}
	if err := os.WriteFile(destPath, content, 0o644); err != nil {
		return fmt.Errorf("write Pi instructions: %w", err)
	}
	log.Printf("[PROVISIONER] Wrote Pi instructions to %s", destPath)
	return nil
}

func piMCPServers(settings *sessionsettings.SessionSettings) map[string]interface{} {
	if settings == nil {
		return nil
	}
	if len(settings.Codex.MCPServers) > 0 {
		return settings.Codex.MCPServers
	}
	if len(settings.Claude.MCPServers) > 0 {
		return settings.Claude.MCPServers
	}
	return nil
}

func writePiMCPServers(settingsPath string, mcpServers map[string]interface{}) error {
	if len(mcpServers) == 0 {
		return nil
	}
	if strings.TrimSpace(settingsPath) == "" {
		return fmt.Errorf("settings path must be set")
	}

	settingsJSON := make(map[string]interface{})
	if data, err := os.ReadFile(settingsPath); err == nil && len(bytes.TrimSpace(data)) > 0 {
		if err := json.Unmarshal(data, &settingsJSON); err != nil {
			return fmt.Errorf("parse existing Pi settings: %w", err)
		}
	} else if err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("read existing Pi settings: %w", err)
	}

	settingsJSON["mcpServers"] = mcpServers

	data, err := json.MarshalIndent(settingsJSON, "", "  ")
	if err != nil {
		return fmt.Errorf("marshal Pi settings: %w", err)
	}
	data = append(data, '\n')

	if err := os.MkdirAll(filepath.Dir(settingsPath), 0o755); err != nil {
		return fmt.Errorf("create Pi settings dir: %w", err)
	}
	if err := os.WriteFile(settingsPath, data, 0o644); err != nil {
		return fmt.Errorf("write Pi settings: %w", err)
	}
	log.Printf("[PROVISIONER] Wrote Pi MCP settings to %s", settingsPath)
	return nil
}

// waitForAgentAPI polls agentapiURL/status until it responds 200 or the
// context is cancelled.  maxRetries × 0.5 s = total wait time.
func waitForAgentAPI(ctx context.Context, agentapiURL string, maxRetries int) error {
	client := &http.Client{Timeout: 3 * time.Second}
	statusURL := agentapiURL + "/status"

	for i := 0; i < maxRetries; i++ {
		select {
		case <-ctx.Done():
			return fmt.Errorf("context cancelled")
		default:
		}

		resp, err := client.Get(statusURL)
		if err == nil {
			_ = resp.Body.Close()
			if resp.StatusCode == http.StatusOK {
				return nil
			}
		}

		time.Sleep(500 * time.Millisecond)
	}
	return fmt.Errorf("agentapi not ready after %d retries", maxRetries)
}

func waitForSciaProxy(ctx context.Context, proxyURL string, timeout time.Duration) {
	if proxyURL == "" {
		return
	}
	healthURL := strings.TrimRight(proxyURL, "/") + "/_scia/healthz"
	client := &http.Client{
		Timeout: 500 * time.Millisecond,
		Transport: &http.Transport{
			Proxy: nil,
		},
	}
	deadline := time.Now().Add(timeout)
	for time.Now().Before(deadline) {
		select {
		case <-ctx.Done():
			return
		default:
		}
		resp, err := client.Get(healthURL)
		if err == nil {
			_ = resp.Body.Close()
			if resp.StatusCode >= 200 && resp.StatusCode < 300 {
				select {
				case <-ctx.Done():
					return
				case <-time.After(2 * time.Second):
				}
				log.Printf("[PROVISIONER] scia proxy is ready at %s", proxyURL)
				return
			}
		}
		time.Sleep(250 * time.Millisecond)
	}
	log.Printf("[PROVISIONER] Warning: scia proxy did not become ready before timeout: %s", proxyURL)
}

func prepareSciaCABundle(ctx context.Context, envMap map[string]string) {
	proxyURL := envMap["AGENTAPI_SCIA_PROXY_URL"]
	if proxyURL == "" {
		return
	}
	waitForSciaProxy(ctx, proxyURL, 15*time.Second)

	sciaCAPath := envMap["NODE_EXTRA_CA_CERTS"]
	if sciaCAPath == "" {
		sciaCAPath = "/etc/scia/mitm/ca.pem"
	}
	bundlePath := envMap["SSL_CERT_FILE"]
	if bundlePath == "" || bundlePath == sciaCAPath {
		return
	}

	sciaCA, err := os.ReadFile(sciaCAPath)
	if err != nil {
		log.Printf("[PROVISIONER] Warning: failed to read scia CA %s: %v", sciaCAPath, err)
		return
	}

	var bundle []byte
	for _, systemPath := range []string{
		"/etc/ssl/certs/ca-certificates.crt",
		"/etc/pki/tls/certs/ca-bundle.crt",
		"/etc/ssl/ca-bundle.pem",
	} {
		systemCA, err := os.ReadFile(systemPath)
		if err == nil && len(systemCA) > 0 {
			bundle = append(bundle, systemCA...)
			if !bytes.HasSuffix(bundle, []byte("\n")) {
				bundle = append(bundle, '\n')
			}
			break
		}
	}
	bundle = append(bundle, sciaCA...)
	if !bytes.HasSuffix(bundle, []byte("\n")) {
		bundle = append(bundle, '\n')
	}
	if err := os.WriteFile(bundlePath, bundle, 0o600); err != nil {
		log.Printf("[PROVISIONER] Warning: failed to write scia CA bundle %s: %v", bundlePath, err)
		return
	}
	log.Printf("[PROVISIONER] Wrote scia CA bundle to %s", bundlePath)
}

// agentStatusResponse is the minimal shape of agentapi's /status response.
type agentStatusResponse struct {
	Status string `json:"status"`
}

// agentMessagesResponse is the minimal shape of agentapi's /messages response.
type agentMessagesResponse struct {
	Messages []struct {
		Role    string `json:"role"`
		Content string `json:"content"`
	} `json:"messages"`
}

// acpSessionResponse is the shape of the ACP bridge's GET /session response.
type acpSessionResponse struct {
	SessionId string `json:"sessionId"`
	Status    string `json:"status"`
}

// acpMessagesResponse is the shape of the ACP bridge's GET /messages response.
// Each message is a raw JSON-RPC 2.0 envelope; we only need to inspect
// the method and the sessionUpdate discriminant inside params.update.
type acpMessagesResponse struct {
	Messages []json.RawMessage `json:"messages"`
}

// sendInitialMessage sends an initial message to agentapi after it has
// started, replicating the logic of initialMessageSenderScript.
func sendInitialMessage(ctx context.Context, agentapiURL, message, agentType string, waitSec int) {
	// ACP sessions use a different transport (JSON-RPC 2.0 over POST /rpc).
	if agentType == "claude-acp" || agentType == "codex-acp" || agentType == "pi-ollama" || agentType == "cursor" {
		sendACPInitialMessage(ctx, agentapiURL, message, waitSec)
		return
	}

	client := &http.Client{Timeout: 5 * time.Second}

	// Check for existing user messages (idempotency / Pod restart).
	if count := countUserMessages(client, agentapiURL); count > 0 {
		log.Printf("[PROVISIONER] User messages already exist (%d), skipping initial message", count)
		return
	}

	// Wait for Claude to be ready (strategy depends on agentType).
	if agentType == "" {
		// Default agentapi: wait for running→stable transition OR stable + non-empty message.
		waitForDefaultAgentReady(ctx, client, agentapiURL)
	} else {
		// Non-default agents: wait for stable.
		waitForStable(ctx, client, agentapiURL, 60)
	}

	// Configured delay before sending.
	log.Printf("[PROVISIONER] Waiting %d second(s) before sending initial message", waitSec)
	select {
	case <-ctx.Done():
		return
	case <-time.After(time.Duration(waitSec) * time.Second):
	}

	// Double-check race condition.
	if count := countUserMessages(client, agentapiURL); count > 0 {
		log.Printf("[PROVISIONER] User messages appeared during wait (%d), skipping", count)
		return
	}

	// Send.
	payload := map[string]string{"content": message, "type": "user"}
	body, _ := json.Marshal(payload)

	for attempt := 1; attempt <= 5; attempt++ {
		log.Printf("[PROVISIONER] Initial message send attempt %d/5", attempt)

		req, _ := http.NewRequestWithContext(ctx, http.MethodPost, agentapiURL+"/message", bytes.NewReader(body))
		req.Header.Set("Content-Type", "application/json")

		resp, err := client.Do(req)
		if err == nil {
			_ = resp.Body.Close()
			if resp.StatusCode == http.StatusOK {
				log.Printf("[PROVISIONER] Initial message sent successfully")
				return
			}
			log.Printf("[PROVISIONER] Send failed (HTTP %d), attempt %d/5", resp.StatusCode, attempt)
		} else {
			log.Printf("[PROVISIONER] Send error: %v, attempt %d/5", err, attempt)
		}

		if attempt < 5 {
			select {
			case <-ctx.Done():
				return
			case <-time.After(3 * time.Second):
			}
		}
	}
	log.Printf("[PROVISIONER] ERROR: Failed to send initial message after 5 attempts")
}

// sendACPInitialMessage sends an initial message to an ACP bridge session
// via POST /rpc (JSON-RPC 2.0 session/prompt).
func sendACPInitialMessage(ctx context.Context, agentapiURL, message string, waitSec int) {
	client := &http.Client{Timeout: 5 * time.Second}

	// Idempotency: check whether user messages already exist in ACP format.
	if count := countACPUserMessages(client, agentapiURL); count > 0 {
		log.Printf("[PROVISIONER] ACP user messages already exist (%d), skipping initial message", count)
		return
	}

	// Wait for the ACP bridge /status to report "stable".
	waitForStable(ctx, client, agentapiURL, 60)

	// Configured delay before sending.
	log.Printf("[PROVISIONER] Waiting %d second(s) before sending ACP initial message", waitSec)
	select {
	case <-ctx.Done():
		return
	case <-time.After(time.Duration(waitSec) * time.Second):
	}

	// Double-check idempotency after wait.
	if count := countACPUserMessages(client, agentapiURL); count > 0 {
		log.Printf("[PROVISIONER] ACP user messages appeared during wait (%d), skipping", count)
		return
	}

	// Fetch the ACP session ID from GET /session.
	acpSessionId, err := getACPSessionId(client, agentapiURL)
	if err != nil {
		log.Printf("[PROVISIONER] ERROR: failed to get ACP session ID: %v", err)
		return
	}
	log.Printf("[PROVISIONER] ACP session ID: %s", acpSessionId)

	// Build JSON-RPC 2.0 session/prompt payload.
	type contentBlock struct {
		Type string `json:"type"`
		Text string `json:"text"`
	}
	type promptParams struct {
		SessionId string         `json:"sessionId"`
		Prompt    []contentBlock `json:"prompt"`
	}
	type rpcRequest struct {
		JSONRPC string       `json:"jsonrpc"`
		ID      int          `json:"id"`
		Method  string       `json:"method"`
		Params  promptParams `json:"params"`
	}
	payload := rpcRequest{
		JSONRPC: "2.0",
		ID:      1,
		Method:  "session/prompt",
		Params: promptParams{
			SessionId: acpSessionId,
			Prompt:    []contentBlock{{Type: "text", Text: message}},
		},
	}
	body, _ := json.Marshal(payload)

	for attempt := 1; attempt <= 5; attempt++ {
		log.Printf("[PROVISIONER] ACP initial message send attempt %d/5", attempt)

		req, _ := http.NewRequestWithContext(ctx, http.MethodPost, agentapiURL+"/rpc", bytes.NewReader(body))
		req.Header.Set("Content-Type", "application/json")

		resp, err := client.Do(req)
		if err == nil {
			_ = resp.Body.Close()
			// Bridge returns 202 Accepted for session/prompt (async).
			if resp.StatusCode == http.StatusAccepted || resp.StatusCode == http.StatusOK {
				log.Printf("[PROVISIONER] ACP initial message sent successfully (HTTP %d)", resp.StatusCode)
				return
			}
			log.Printf("[PROVISIONER] ACP send failed (HTTP %d), attempt %d/5", resp.StatusCode, attempt)
		} else {
			log.Printf("[PROVISIONER] ACP send error: %v, attempt %d/5", err, attempt)
		}

		if attempt < 5 {
			select {
			case <-ctx.Done():
				return
			case <-time.After(3 * time.Second):
			}
		}
	}
	log.Printf("[PROVISIONER] ERROR: Failed to send ACP initial message after 5 attempts")
}

// getACPSessionId fetches the ACP session ID from GET /session.
func getACPSessionId(client *http.Client, agentapiURL string) (string, error) {
	resp, err := client.Get(agentapiURL + "/session")
	if err != nil {
		return "", err
	}
	defer func() { _ = resp.Body.Close() }()
	var sr acpSessionResponse
	if err := json.NewDecoder(resp.Body).Decode(&sr); err != nil {
		return "", err
	}
	if sr.SessionId == "" {
		return "", fmt.Errorf("empty sessionId in /session response")
	}
	return sr.SessionId, nil
}

// countACPUserMessages returns the number of user_message_chunk events in the
// ACP bridge's GET /messages history. Used for idempotency on Pod restarts.
func countACPUserMessages(client *http.Client, agentapiURL string) int {
	resp, err := client.Get(agentapiURL + "/messages")
	if err != nil {
		return 0
	}
	defer func() { _ = resp.Body.Close() }()

	var mr acpMessagesResponse
	if err := json.NewDecoder(resp.Body).Decode(&mr); err != nil {
		return 0
	}

	// Each element is a raw JSON-RPC 2.0 message. We look for:
	//   { "method": "session/update", "params": { "update": { "sessionUpdate": "user_message_chunk" } } }
	type acpUpdateParams struct {
		Update struct {
			SessionUpdate string `json:"sessionUpdate"`
		} `json:"update"`
	}
	type acpMsg struct {
		Method string          `json:"method"`
		Params acpUpdateParams `json:"params"`
	}
	count := 0
	for _, raw := range mr.Messages {
		var m acpMsg
		if err := json.Unmarshal(raw, &m); err != nil {
			continue
		}
		if m.Method == "session/update" && m.Params.Update.SessionUpdate == "user_message_chunk" {
			count++
		}
	}
	return count
}

// waitForDefaultAgentReady uses the two-phase strategy from the original shell
// script: first tries to catch "running→stable" within 10 s, then falls back
// to "stable + non-empty message" for up to 60 s.
func waitForDefaultAgentReady(ctx context.Context, client *http.Client, agentapiURL string) {
	log.Printf("[PROVISIONER] Waiting for agent ready (phase 1: running→stable, 10s timeout)")

	sawRunning := false
	for i := 0; i < 10; i++ {
		select {
		case <-ctx.Done():
			return
		case <-time.After(time.Second):
		}

		st := getAgentStatus(client, agentapiURL)
		if st == "running" {
			sawRunning = true
		}
		if sawRunning && st == "stable" {
			if countNonEmptyMessages(client, agentapiURL) > 0 {
				log.Printf("[PROVISIONER] Phase 1: running→stable transition detected")
				return
			}
		}
	}

	// Phase 2 fallback.
	log.Printf("[PROVISIONER] Phase 1 timed out (sawRunning=%v), falling back to stable+non-empty check", sawRunning)
	for i := 0; i < 60; i++ {
		select {
		case <-ctx.Done():
			return
		case <-time.After(time.Second):
		}

		if getAgentStatus(client, agentapiURL) == "stable" && countNonEmptyMessages(client, agentapiURL) > 0 {
			log.Printf("[PROVISIONER] Phase 2: agent stable with non-empty messages")
			return
		}
	}
	log.Printf("[PROVISIONER] WARNING: agent not fully ready after 70s, sending anyway")
}

// waitForStable polls until agentapi reports "stable" or the context is done.
func waitForStable(ctx context.Context, client *http.Client, agentapiURL string, maxRetries int) {
	for i := 0; i < maxRetries; i++ {
		select {
		case <-ctx.Done():
			return
		case <-time.After(time.Second):
		}
		if getAgentStatus(client, agentapiURL) == "stable" {
			return
		}
	}
	log.Printf("[PROVISIONER] WARNING: agent not stable after %d retries", maxRetries)
}

// getAgentStatus fetches /status and returns the "status" field value.
func getAgentStatus(client *http.Client, agentapiURL string) string {
	resp, err := client.Get(agentapiURL + "/status")
	if err != nil {
		return ""
	}
	defer func() { _ = resp.Body.Close() }()

	var sr agentStatusResponse
	if err := json.NewDecoder(resp.Body).Decode(&sr); err != nil {
		return ""
	}
	return sr.Status
}

// countUserMessages returns the number of messages with role "user".
func countUserMessages(client *http.Client, agentapiURL string) int {
	resp, err := client.Get(agentapiURL + "/messages")
	if err != nil {
		return 0
	}
	defer func() { _ = resp.Body.Close() }()

	var mr agentMessagesResponse
	if err := json.NewDecoder(resp.Body).Decode(&mr); err != nil {
		return 0
	}
	count := 0
	for _, m := range mr.Messages {
		if m.Role == "user" {
			count++
		}
	}
	return count
}

// countNonEmptyMessages returns the number of messages with non-empty content.
func countNonEmptyMessages(client *http.Client, agentapiURL string) int {
	resp, err := client.Get(agentapiURL + "/messages")
	if err != nil {
		return 0
	}
	defer func() { _ = resp.Body.Close() }()

	var mr agentMessagesResponse
	if err := json.NewDecoder(resp.Body).Decode(&mr); err != nil {
		return 0
	}
	count := 0
	for _, m := range mr.Messages {
		if m.Content != "" {
			count++
		}
	}
	return count
}

// fetchAndInjectMemory fetches session memory from the proxy and appends it to
// CLAUDE.md, replicating the bash memory injection in buildClaudeStartCommand.
// getEnv returns the value of key from envMap if present, falling back to os.Getenv.
func getEnv(envMap map[string]string, key string) string {
	if v, ok := envMap[key]; ok {
		return v
	}
	return os.Getenv(key)
}

func (s *Server) fetchAndInjectMemory(envMap map[string]string) {
	memoryKeyFlags := getEnv(envMap, "MEMORY_KEY_FLAGS")
	if memoryKeyFlags == "" {
		return
	}

	proxyHost := getEnv(envMap, "AGENTAPI_PROXY_SERVICE_HOST")
	proxyPort := getEnv(envMap, "AGENTAPI_PROXY_SERVICE_PORT_HTTP")
	if proxyHost == "" || proxyPort == "" {
		log.Printf("[PROVISIONER] AGENTAPI_PROXY_SERVICE_HOST or PORT not set, skipping memory fetch")
		return
	}
	proxyEndpoint := fmt.Sprintf("http://%s:%s", proxyHost, proxyPort)

	scope := getEnv(envMap, "AGENTAPI_SCOPE")
	if scope == "" {
		scope = "user"
	}

	args := []string{
		"client", "memory", "list",
		"--scope", scope,
		"--union",
		"--format", "markdown",
		"--endpoint", proxyEndpoint,
	}

	// Append memory key flags (e.g. "--key foo --key bar").
	args = append(args, strings.Fields(memoryKeyFlags)...)

	if scope == "team" {
		if teamID := getEnv(envMap, "AGENTAPI_TEAM_ID"); teamID != "" {
			args = append(args, "--team-id", teamID)
		}
	}

	log.Printf("[PROVISIONER] Fetching session memory (keys: %s)", memoryKeyFlags)
	out, err := exec.Command("agentapi-proxy", args...).Output()
	if err != nil || len(bytes.TrimSpace(out)) == 0 {
		log.Printf("[PROVISIONER] No memory found for this session (non-fatal)")
		return
	}

	f, err := os.OpenFile(claudeMDPath, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0o644)
	if err != nil {
		log.Printf("[PROVISIONER] Warning: failed to open CLAUDE.md for memory injection: %v", err)
		return
	}
	defer func() { _ = f.Close() }()

	_, _ = fmt.Fprintf(f, "\n---\n\n%s\n", bytes.TrimSpace(out))
	log.Printf("[PROVISIONER] Memory injected into CLAUDE.md")
}

// loadEnvFile reads a KEY=VALUE env file and returns the entries as a map.
// Lines starting with '#' and blank lines are ignored.
func loadEnvFile(path string) map[string]string {
	result := make(map[string]string)
	f, err := os.Open(path)
	if err != nil {
		return result
	}
	defer func() { _ = f.Close() }()

	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		idx := strings.IndexByte(line, '=')
		if idx < 0 {
			continue
		}
		key := line[:idx]
		val := unquoteValue(line[idx+1:])
		result[key] = val
	}
	return result
}

// unquoteValue removes surrounding single or double quotes from a shell value.
func unquoteValue(v string) string {
	if len(v) >= 2 {
		if (v[0] == '"' && v[len(v)-1] == '"') || (v[0] == '\'' && v[len(v)-1] == '\'') {
			return v[1 : len(v)-1]
		}
	}
	return v
}

// writeWebhookPayloadFile writes the webhook payload JSON string to
// webhookPayloadPath.  It is a no-op when the file already exists, which is
// the case for non-stock sessions where a read-only Kubernetes Secret volume
// provides the file.  For stock sessions the volume is absent, so the
// provisioner writes the file itself to ensure the agent always finds the
// payload at the same well-known path.
func writeWebhookPayloadFile(payload string) {
	writeWebhookPayloadFileToPath(webhookPayloadPath, payload)
}

// writeWebhookPayloadFileToPath is the path-parameterised implementation
// shared by writeWebhookPayloadFile and unit tests.
func writeWebhookPayloadFileToPath(path, payload string) {
	if _, err := os.Stat(path); err == nil {
		// File already present (non-stock session: Secret volume mount).
		log.Printf("[PROVISIONER] Webhook payload file already exists at %s, skipping write", path)
		return
	}

	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		log.Printf("[PROVISIONER] Warning: failed to create webhook payload dir %s: %v", dir, err)
		return
	}

	if err := os.WriteFile(path, []byte(payload), 0o644); err != nil {
		log.Printf("[PROVISIONER] Warning: failed to write webhook payload file %s: %v", path, err)
		return
	}

	log.Printf("[PROVISIONER] Wrote webhook payload to %s (%d bytes)", path, len(payload))
}

// mergeEnv takes the current os.Environ() slice and overlays envMap entries.
// The envMap values take precedence (session-specific overrides).
func mergeEnv(base []string, overlay map[string]string) []string {
	// Build a map from base env (last occurrence wins if duplicated).
	merged := make(map[string]string, len(base)+len(overlay))
	for _, kv := range base {
		idx := strings.IndexByte(kv, '=')
		if idx < 0 {
			continue
		}
		merged[kv[:idx]] = kv[idx+1:]
	}
	for k, v := range overlay {
		merged[k] = v
	}

	result := make([]string, 0, len(merged))
	for k, v := range merged {
		result = append(result, k+"="+v)
	}
	sort.Strings(result)
	return result
}

// configureNetworkFilterPolicy calls POST /policy on the nfa control server to
// apply the concrete sandbox policy from SessionSettings. This is important for
// stock sessions: their sandbox sidecar starts before the user's policy/count
// mode settings are known.
func configureNetworkFilterPolicy(sandbox *sessionsettings.SandboxConfig) {
	if sandbox == nil || !sandbox.Enabled {
		return
	}
	payload := map[string]interface{}{
		"allowed":    sessionsettings.SandboxAllowedDomains(sandbox.AllowedDomains, sandbox.DeniedDomains),
		"denied":     sandbox.DeniedDomains,
		"count_mode": sandbox.CountMode,
	}
	data, err := json.Marshal(payload)
	if err != nil {
		log.Printf("[PROVISIONER] network-filter configure-policy marshal: %v", err)
		return
	}
	resp, err := http.Post("http://127.0.0.1:3129/policy", "application/json", bytes.NewReader(data))
	if err != nil {
		log.Printf("[PROVISIONER] network-filter configure-policy: %v (no sandbox sidecar?)", err)
		return
	}
	defer resp.Body.Close() //nolint:errcheck
	log.Printf("[PROVISIONER] network-filter policy configured (status %s, count_mode=%t)", resp.Status, sandbox.CountMode)
}

// enableNetworkFilterPolicy calls POST /enable-policy on the network-filter
// control server (localhost:3129) so that the sandbox policy takes effect after
// the agent has fully started. The call is best-effort: if there is no sandbox
// sidecar the connection is refused and the error is silently ignored.
func enableNetworkFilterPolicy() {
	resp, err := http.Post("http://127.0.0.1:3129/enable-policy", "", nil)
	if err != nil {
		log.Printf("[PROVISIONER] network-filter enable-policy: %v (no sandbox sidecar?)", err)
		return
	}
	defer resp.Body.Close() //nolint:errcheck
	log.Printf("[PROVISIONER] network-filter policy enabled (status %s)", resp.Status)
}
