package entities

import (
	"errors"
	"time"
)

// APITokenScope is the scope of an API token. It mirrors ResourceScope but is
// kept as a dedicated type so API-token code does not depend on session
// entities.
type APITokenScope string

const (
	// APITokenScopeUser marks a personal token that authenticates as its owner.
	APITokenScopeUser APITokenScope = "user"
	// APITokenScopeTeam marks a team token that authenticates as a
	// team-scoped service account identity.
	APITokenScopeTeam APITokenScope = "team"
)

// ErrAPITokenNotFound is returned by repositories when an API token is not
// found. It is intentionally generic so callers cannot use it to distinguish
// tokens across scopes (avoids cross-scope existence leakage).
var ErrAPITokenNotFound = errors.New("api token not found")

// ErrAPITokenAlreadyExists is returned when creating a token whose ID already
// exists. This enables idempotent migration behavior.
var ErrAPITokenAlreadyExists = errors.New("api token already exists")

// APIToken represents a named, revocable API token owned by a user or a team.
//
// A personal token (scope == APITokenScopeUser) authenticates as its owner.
// A team token (scope == APITokenScopeTeam) authenticates as a team-scoped
// service account identity (UserID is the service-account user id, e.g.
// "sa-<team>").
//
// The plaintext Secret is stored only inside the backing Kubernetes Secret and
// is returned to the caller exactly once, on creation. It must never be logged
// or returned by list/get operations.
type APIToken struct {
	id            string
	secret        string // plaintext token; returned only once on creation
	displayPrefix string // short, safe prefix for display on list/get
	name          string
	scope         APITokenScope
	userID        UserID // identity the token authenticates as
	teamID        string // populated when scope == APITokenScopeTeam
	permissions   []Permission
	expiresAt     *time.Time
	createdBy     UserID // the user that created the token
	createdAt     time.Time
	updatedAt     time.Time
}

// NewAPIToken creates a new APIToken with the given immutable identity fields.
// Timestamps are set to now. The secret and display prefix must already be
// generated by the caller (or restored from storage).
func NewAPIToken(
	id, secret, displayPrefix, name string,
	scope APITokenScope,
	userID UserID,
	teamID string,
	permissions []Permission,
	expiresAt *time.Time,
	createdBy UserID,
) *APIToken {
	now := time.Now()
	t := &APIToken{
		id:            id,
		secret:        secret,
		displayPrefix: displayPrefix,
		name:          name,
		scope:         scope,
		userID:        userID,
		teamID:        teamID,
		permissions:   copyPermissions(permissions),
		expiresAt:     copyTime(expiresAt),
		createdBy:     createdBy,
		createdAt:     now,
		updatedAt:     now,
	}
	return t
}

// RestoreAPIToken reconstructs an APIToken from persisted storage, preserving
// the original timestamps. It is intended for repository/deserialization use.
func RestoreAPIToken(
	id, secret, displayPrefix, name string,
	scope APITokenScope,
	userID UserID,
	teamID string,
	permissions []Permission,
	expiresAt *time.Time,
	createdBy UserID,
	createdAt, updatedAt time.Time,
) *APIToken {
	return &APIToken{
		id:            id,
		secret:        secret,
		displayPrefix: displayPrefix,
		name:          name,
		scope:         scope,
		userID:        userID,
		teamID:        teamID,
		permissions:   copyPermissions(permissions),
		expiresAt:     copyTime(expiresAt),
		createdBy:     createdBy,
		createdAt:     createdAt,
		updatedAt:     updatedAt,
	}
}

// ID returns the opaque, public token ID (used in URLs).
func (t *APIToken) ID() string { return t.id }

// Secret returns the plaintext token. This must NEVER be exposed through
// list/get responses; it is only safe to return on creation.
func (t *APIToken) Secret() string { return t.secret }

// DisplayPrefix returns a short, safe prefix of the secret for display.
func (t *APIToken) DisplayPrefix() string { return t.displayPrefix }

// Name returns the human-readable name of the token.
func (t *APIToken) Name() string { return t.name }

// Scope returns the token scope (user or team).
func (t *APIToken) Scope() APITokenScope { return t.scope }

// UserID returns the identity the token authenticates as.
func (t *APIToken) UserID() UserID { return t.userID }

// TeamID returns the team ID (populated only when scope == APITokenScopeTeam).
func (t *APIToken) TeamID() string { return t.teamID }

// Permissions returns a copy of the token permissions.
func (t *APIToken) Permissions() []Permission { return copyPermissions(t.permissions) }

// ExpiresAt returns the expiration time, or nil if the token never expires.
func (t *APIToken) ExpiresAt() *time.Time { return copyTime(t.expiresAt) }

// CreatedBy returns the user ID of the token creator.
func (t *APIToken) CreatedBy() UserID { return t.createdBy }

// CreatedAt returns the creation timestamp.
func (t *APIToken) CreatedAt() time.Time { return t.createdAt }

// UpdatedAt returns the last update timestamp.
func (t *APIToken) UpdatedAt() time.Time { return t.updatedAt }

// SetName updates the name and the updated timestamp.
func (t *APIToken) SetName(name string) {
	t.name = name
	t.updatedAt = time.Now()
}

// SetCreatedAt sets the created-at timestamp (for deserialization).
func (t *APIToken) SetCreatedAt(ts time.Time) { t.createdAt = ts }

// SetUpdatedAt sets the updated-at timestamp (for deserialization).
func (t *APIToken) SetUpdatedAt(ts time.Time) { t.updatedAt = ts }

// IsExpired returns true if the token has an expiration time that is in the
// past.
func (t *APIToken) IsExpired() bool {
	if t.expiresAt == nil {
		return false
	}
	return time.Now().After(*t.expiresAt)
}

// HasPermission reports whether the token grants the given permission. The
// admin permission grants everything.
func (t *APIToken) HasPermission(p Permission) bool {
	for _, perm := range t.permissions {
		if perm == p || perm == PermissionAdmin {
			return true
		}
	}
	return false
}

// Validate returns an error if the token is in an invalid state.
func (t *APIToken) Validate() error {
	if t.id == "" {
		return errors.New("api token id cannot be empty")
	}
	if t.secret == "" {
		return errors.New("api token secret cannot be empty")
	}
	if t.scope != APITokenScopeUser && t.scope != APITokenScopeTeam {
		return errors.New("api token scope must be 'user' or 'team'")
	}
	if t.userID == "" {
		return errors.New("api token user id cannot be empty")
	}
	if t.scope == APITokenScopeTeam && t.teamID == "" {
		return errors.New("api token team id is required when scope is 'team'")
	}
	if t.scope == APITokenScopeUser && t.teamID != "" {
		return errors.New("api token team id must be empty when scope is 'user'")
	}
	if t.createdBy == "" {
		return errors.New("api token created_by cannot be empty")
	}
	if len(t.permissions) == 0 {
		return errors.New("api token permissions cannot be empty")
	}
	if t.createdAt.IsZero() {
		return errors.New("api token created_at cannot be zero")
	}
	if t.updatedAt.IsZero() {
		return errors.New("api token updated_at cannot be zero")
	}
	return nil
}

// copyPermissions returns a defensive copy of the given permission slice.
func copyPermissions(in []Permission) []Permission {
	if in == nil {
		return []Permission{}
	}
	out := make([]Permission, len(in))
	copy(out, in)
	return out
}

// copyTime returns a defensive copy of the given time pointer.
func copyTime(t *time.Time) *time.Time {
	if t == nil {
		return nil
	}
	cp := *t
	return &cp
}
