{{- if and .Values.config.persistence.s3.accessKey .Values.config.persistence.s3.secretKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agentapi-proxy.fullname" . }}-s3-credentials
  labels:
    {{- include "agentapi-proxy.labels" . | nindent 4 }}
type: Opaque
data:
  access-key: {{ .Values.config.persistence.s3.accessKey | b64enc }}
  secret-key: {{ .Values.config.persistence.s3.secretKey | b64enc }}
{{- end }}