{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agentapi-proxy.fullname" . }}-secrets
  labels:
    {{- include "agentapi-proxy.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end }}