apiVersion: v1
kind: Service
metadata:
  name: {{ include "agentapi-proxy.fullname" . }}
  labels:
    {{- include "agentapi-proxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.agentapiPort }}
      targetPort: {{ .Values.service.agentapiPort }}
      protocol: TCP
      name: agentapi-base
  selector:
    {{- include "agentapi-proxy.selectorLabels" . | nindent 4 }}