apiVersion: v1
kind: ConfigMap
metadata:
  name: agentapi-proxy-config
  namespace: default
data:
  config.json: |
    {
      "start_port": 9000,
      "auth": {
        "type": "api_key",
        "api_keys": []
      },
      "persistence": {
        "type": "file",
        "file_path": "/home/agentapi/sessions.json"
      }
    }
  CLAUDE_ARGS: ""
  GITHUB_URL: "https://github.com"