apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - configmap.yaml
  - secret.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  app: agentapi-proxy
  version: "0.18.0"

images:
  - name: ghcr.io/takutakahashi/agentapi-proxy
    newTag: "0.18.0"