apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: agentapi-proxy-data
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard