apiVersion: v1
kind: Secret
metadata:
  name: agentapi-proxy-secrets
  namespace: default
type: Opaque
stringData:
  # GitHub authentication - choose one method:
  # Option 1: Personal Access Token
  GITHUB_TOKEN: "your-github-pat-here"
  
  # Option 2: GitHub App authentication
  # GITHUB_APP_ID: "your-github-app-id"
  # GITHUB_APP_PEM: |
  #   -----BEGIN RSA PRIVATE KEY-----
  #   your-github-app-private-key-here
  #   -----END RSA PRIVATE KEY-----
  
  # API Keys for authentication (comma-separated)
  API_KEYS: "key1,key2,key3"