name: E2E Tests

on:
  workflow_run:
    workflows: ["Docker Build and Push"]
    types:
      - completed
    branches: [ main ]

env:
  GO_VERSION: "1.21"

jobs:
  e2e:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Run E2E tests
      run: make e2e