name: Manual Docker Build

on:
  workflow_dispatch:
    inputs:
      commit_hash:
        description: 'Commit hash to build (optional, defaults to current commit)'
        required: false
        default: ''
      tag_suffix:
        description: 'Additional tag suffix (optional)'
        required: false
        default: ''

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.commit_hash || github.sha }}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract commit hash
        id: commit
        run: |
          COMMIT_HASH=$(git rev-parse --short HEAD)
          echo "commit_hash=${COMMIT_HASH}" >> $GITHUB_OUTPUT
          echo "Building commit: ${COMMIT_HASH}"
      
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=raw,value=${{ steps.commit.outputs.commit_hash }}${{ github.event.inputs.tag_suffix && format('-{0}', github.event.inputs.tag_suffix) || '' }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            AGENTAPI_VERSION=v0.2.1

      - name: Output image tags
        run: |
          echo "Built and pushed the following tags:"
          echo "${{ steps.meta.outputs.tags }}"